/*
 * File: actions/types.js
 * Desc: defines actions what will be used to dispatch reducers
 * Author: DuyNg (duy@megadrupal.com)
 * Created: 2018-07-18 20:29:19
 */
const asyncActionType = type => ({
  REQUEST: `${type}_REQUEST`,
  SUCCESS: `${type}_SUCCESS`,
  FAILED: `${type}_FAILED`
});

export const FETCH_FIRST_TOKEN = 'FETCH_FIRST_TOKEN';
export const FETCH_FIRST_TOKEN_SUCCESS = 'FETCH_FIRST_TOKEN_SUCCESS';
export const FETCH_FIRST_TOKEN_FAILED = 'FETCH_FIRST_TOKEN_FAILED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SIGNOUT = 'SIGNOUT';
export const SHOW_AUTH_POPUP = 'SHOW_AUTH_POPUP';
export const HIDE_AUTH_POPUP = 'HIDE_AUTH_POPUP';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_REDIRECT = 'UPDATE_REDIRECT';

export const FETCH_CONSTANTS = 'FETCH_CONSTANTS';
export const FETCH_CONSTANTS_SUCCESS = 'FETCH_CONSTANTS_SUCCESS';
export const FETCH_CONSTANTS_FAILED = 'FETCH_CONSTANTS_FAILED';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const FETCH_CITIES = 'FETCH_CITIES';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_FAILED = 'FETCH_CITIES_FAILED';

export const FETCH_CANDIDATES = 'FETCH_CANDIDATES';
export const FETCH_CANDIDATES_SUCCESS = 'FETCH_CANDIDATES_SUCCESS';
export const FETCH_CANDIDATES_FAILED = 'FETCH_CANDIDATES_FAILED';
export const FETCH_CANDIDATE_INFO = 'FETCH_CANDIDATE_INFO';
export const FETCH_CANDIDATE_INFO_SUCCESS = 'FETCH_CANDIDATE_INFO_SUCCESS';
export const FETCH_CANDIDATE_INFO_FAILED = 'FETCH_CANDIDATE_INFO_FAILED';
export const FETCH_SAVED_CANDIDATES = 'FETCH_SAVED_CANDIDATES';
export const FETCH_SAVED_CANDIDATES_SUCCESS = 'FETCH_SAVED_CANDIDATES_SUCCESS';
export const FETCH_SAVED_CANDIDATES_FAILED = 'FETCH_SAVED_CANDIDATES_FAILED';
export const FETCH_VIEWED_CANDIDATES = 'FETCH_VIEWED_CANDIDATES';
export const FETCH_VIEWED_CANDIDATES_SUCCESS = 'FETCH_VIEWED_CANDIDATES_SUCCESS';
export const FETCH_VIEWED_CANDIDATES_FAILED = 'FETCH_VIEWED_CANDIDATES_FAILED';
export const FETCH_APPLIED_CANDIDATES = 'FETCH_APPLIED_CANDIDATES';
export const FETCH_APPLIED_CANDIDATES_SUCCESS = 'FETCH_APPLIED_CANDIDATES_SUCCESS';
export const FETCH_APPLIED_CANDIDATES_FAILED = 'FETCH_APPLIED_CANDIDATES_FAILED';

export const FETCH_COMPANY_INFO = 'FETCH_CITIES';
export const FETCH_COMPANY_INFO_SUCCESS = 'FETCH_COMPANY_INFO_SUCCESS';
export const FETCH_COMPANY_INFO_FAILED = 'FETCH_COMPANY_INFO_FAILED';

export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAILED = 'FETCH_SEARCH_FAILED';

export const FETCH_NOTIFCATIONS = 'FETCH_NOTIFCATIONS';
export const FETCH_NOTIFCATIONS_SUCCESS = 'FETCH_NOTIFCATIONS_SUCCESS';
export const FETCH_NOTIFCATIONS_FAILED = 'FETCH_NOTIFCATIONS_FAILED';
export const MARK_READ_NOTIFICATION = 'MARK_READ_NOTIFICATION';
export const MARK_READ_ALL_NOTIFICATION = 'MARK_READ_ALL_NOTIFICATION';

export const FETCH_RESUMES = 'FETCH_RESUMES';
export const FETCH_RESUMES_SUCCESS = 'FETCH_RESUMES_SUCCESS';
export const FETCH_RESUMES_FAILED = 'FETCH_RESUMES_FAILED';
export const DELETE_RESUME_SUCCESS = 'DELETE_RESUME_SUCCESS';
export const CHANGE_RESUME_SEARCHING_STATUS = 'CHANGE_RESUME_SEARCHING_STATUS';
export const CHANGE_RESUME_SEARCHING_STATUS_SUCCESS = 'CHANGE_RESUME_SEARCHING_STATUS_SUCCESS';
export const CHANGE_RESUME_SEARCHING_STATUS_FAILED = 'CHANGE_RESUME_SEARCHING_STATUS_FAILED';
